import type { Park, ParkId, Ride } from "./types";

export const PARKS: Park[] = [
  {
    id: "magic-kingdom",
    name: "Magic Kingdom",
    shortName: "MK",
    tagline: "The classic Disney experience",
    status: "Open",
    crowd: "High",
    hours: "9:00 AM — 11:00 PM",
    themeHex: "#6366f1",
    themeAccentHex: "#a5b4fc",
  },
  {
    id: "epcot",
    name: "EPCOT",
    shortName: "EP",
    tagline: "Future tech meets world cultures",
    status: "Open",
    crowd: "Moderate",
    hours: "9:00 AM — 9:00 PM",
    themeHex: "#0ea5e9",
    themeAccentHex: "#7dd3fc",
  },
  {
    id: "hollywood-studios",
    name: "Hollywood Studios",
    shortName: "HS",
    tagline: "Movies, magic, and Star Wars",
    status: "Open",
    crowd: "High",
    hours: "8:30 AM — 9:30 PM",
    themeHex: "#ef4444",
    themeAccentHex: "#fca5a5",
  },
  {
    id: "animal-kingdom",
    name: "Animal Kingdom",
    shortName: "AK",
    tagline: "Wildlife, adventure, and Pandora",
    status: "Open",
    crowd: "Low",
    hours: "8:00 AM — 8:00 PM",
    themeHex: "#10b981",
    themeAccentHex: "#6ee7b7",
  },
];

export const RIDES: Ride[] = [
  // Magic Kingdom
  {
    id: "mk-space-mountain",
    parkId: "magic-kingdom",
    name: "Space Mountain",
    land: "Tomorrowland",
    category: "thrill",
    description:
      "Blast through the cosmos on a high-speed indoor coaster in near total darkness.",
    x: 72,
    y: 38,
    baseWait: 65,
    trend: "up",
    lightningLane: true,
    height: '44" (112 cm) minimum',
  },
  {
    id: "mk-seven-dwarfs",
    parkId: "magic-kingdom",
    name: "Seven Dwarfs Mine Train",
    land: "Fantasyland",
    category: "family",
    description:
      "A swaying mine-cart coaster through the diamond mines from Snow White.",
    x: 50,
    y: 30,
    baseWait: 80,
    trend: "up",
    lightningLane: true,
    height: '38" (97 cm) minimum',
  },
  {
    id: "mk-thunder-mountain",
    parkId: "magic-kingdom",
    name: "Big Thunder Mountain",
    land: "Frontierland",
    category: "thrill",
    description:
      "The wildest ride in the wilderness — a runaway mine train coaster.",
    x: 26,
    y: 40,
    baseWait: 45,
    trend: "flat",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "mk-pirates",
    parkId: "magic-kingdom",
    name: "Pirates of the Caribbean",
    land: "Adventureland",
    category: "family",
    description:
      "A scenic boat ride through swashbuckling pirate adventures.",
    x: 22,
    y: 58,
    baseWait: 25,
    trend: "down",
    lightningLane: false,
  },
  {
    id: "mk-haunted-mansion",
    parkId: "magic-kingdom",
    name: "Haunted Mansion",
    land: "Liberty Square",
    category: "family",
    description:
      "Doom buggies tour a manor with 999 happy haunts — and room for one more.",
    x: 38,
    y: 50,
    baseWait: 35,
    trend: "flat",
    lightningLane: true,
  },
  {
    id: "mk-jungle-cruise",
    parkId: "magic-kingdom",
    name: "Jungle Cruise",
    land: "Adventureland",
    category: "family",
    description:
      "A skipper-led river cruise through the rivers of the world. Puns included.",
    x: 30,
    y: 62,
    baseWait: 40,
    trend: "up",
    lightningLane: true,
  },
  {
    id: "mk-peter-pan",
    parkId: "magic-kingdom",
    name: "Peter Pan's Flight",
    land: "Fantasyland",
    category: "kids",
    description: "Soar over London and Neverland aboard a flying pirate ship.",
    x: 56,
    y: 36,
    baseWait: 70,
    trend: "up",
    lightningLane: true,
  },
  {
    id: "mk-tiana",
    parkId: "magic-kingdom",
    name: "Tiana's Bayou Adventure",
    land: "Frontierland",
    category: "family",
    description:
      "Plunge into the bayou for a musical journey with Princess Tiana and friends.",
    x: 18,
    y: 48,
    baseWait: 95,
    trend: "up",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },

  // EPCOT
  {
    id: "ep-guardians",
    parkId: "epcot",
    name: "Guardians of the Galaxy: Cosmic Rewind",
    land: "World Discovery",
    category: "thrill",
    description:
      "A reverse-launch coaster that rotates 360° to follow the action.",
    x: 64,
    y: 38,
    baseWait: 90,
    trend: "up",
    lightningLane: true,
    height: '42" (107 cm) minimum',
  },
  {
    id: "ep-test-track",
    parkId: "epcot",
    name: "Test Track",
    land: "World Discovery",
    category: "thrill",
    description:
      "Design your own concept car, then put it through its paces at 60+ mph.",
    x: 70,
    y: 56,
    baseWait: 60,
    trend: "flat",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "ep-soarin",
    parkId: "epcot",
    name: "Soarin' Around the World",
    land: "World Nature",
    category: "family",
    description:
      "Hang glide over the planet's most iconic landmarks in stunning IMAX scale.",
    x: 30,
    y: 46,
    baseWait: 45,
    trend: "down",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "ep-frozen",
    parkId: "epcot",
    name: "Frozen Ever After",
    land: "World Showcase — Norway",
    category: "family",
    description:
      "A musical boat ride through Arendelle with Anna, Elsa, and Olaf.",
    x: 24,
    y: 70,
    baseWait: 75,
    trend: "up",
    lightningLane: true,
  },
  {
    id: "ep-remy",
    parkId: "epcot",
    name: "Remy's Ratatouille Adventure",
    land: "World Showcase — France",
    category: "family",
    description: "Shrink to rat-size and scurry through Gusteau's restaurant.",
    x: 38,
    y: 78,
    baseWait: 55,
    trend: "flat",
    lightningLane: true,
  },
  {
    id: "ep-spaceship-earth",
    parkId: "epcot",
    name: "Spaceship Earth",
    land: "World Celebration",
    category: "family",
    description:
      "An iconic journey through the history of human communication.",
    x: 50,
    y: 28,
    baseWait: 20,
    trend: "down",
    lightningLane: false,
  },

  // Hollywood Studios
  {
    id: "hs-rise",
    parkId: "hollywood-studios",
    name: "Rise of the Resistance",
    land: "Galaxy's Edge",
    category: "thrill",
    description:
      "The most ambitious Disney ride ever — board a Star Destroyer and escape.",
    x: 22,
    y: 38,
    baseWait: 110,
    trend: "up",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "hs-millennium",
    parkId: "hollywood-studios",
    name: "Millennium Falcon: Smugglers Run",
    land: "Galaxy's Edge",
    category: "family",
    description: "Pilot the fastest hunk of junk in the galaxy on a smuggling job.",
    x: 28,
    y: 50,
    baseWait: 50,
    trend: "flat",
    lightningLane: true,
    height: '38" (97 cm) minimum',
  },
  {
    id: "hs-slinky",
    parkId: "hollywood-studios",
    name: "Slinky Dog Dash",
    land: "Toy Story Land",
    category: "family",
    description: "A backyard family coaster that twists, turns, and dashes.",
    x: 60,
    y: 64,
    baseWait: 70,
    trend: "up",
    lightningLane: true,
    height: '38" (97 cm) minimum',
  },
  {
    id: "hs-tower",
    parkId: "hollywood-studios",
    name: "Tower of Terror",
    land: "Sunset Boulevard",
    category: "thrill",
    description: "A haunted hotel free-fall drop through the Twilight Zone.",
    x: 78,
    y: 44,
    baseWait: 55,
    trend: "flat",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "hs-rocknroller",
    parkId: "hollywood-studios",
    name: "Rock 'n' Roller Coaster",
    land: "Sunset Boulevard",
    category: "thrill",
    description: "Launched coaster scored to Aerosmith. 0–60 in 2.8 seconds.",
    x: 82,
    y: 52,
    baseWait: 65,
    trend: "up",
    lightningLane: true,
    height: '48" (122 cm) minimum',
  },
  {
    id: "hs-runaway-railway",
    parkId: "hollywood-studios",
    name: "Mickey & Minnie's Runaway Railway",
    land: "Hollywood Boulevard",
    category: "family",
    description:
      "Step into a Mickey Mouse cartoon for a wonderfully unpredictable ride.",
    x: 50,
    y: 30,
    baseWait: 40,
    trend: "down",
    lightningLane: true,
  },

  // Animal Kingdom
  {
    id: "ak-flight-of-passage",
    parkId: "animal-kingdom",
    name: "Avatar Flight of Passage",
    land: "Pandora",
    category: "thrill",
    description:
      "Bond with a banshee and soar across the moon of Pandora in 3D.",
    x: 26,
    y: 50,
    baseWait: 105,
    trend: "up",
    lightningLane: true,
    height: '44" (112 cm) minimum',
  },
  {
    id: "ak-navi",
    parkId: "animal-kingdom",
    name: "Na'vi River Journey",
    land: "Pandora",
    category: "family",
    description: "A serene boat ride through the bioluminescent rainforest.",
    x: 32,
    y: 60,
    baseWait: 60,
    trend: "flat",
    lightningLane: true,
  },
  {
    id: "ak-everest",
    parkId: "animal-kingdom",
    name: "Expedition Everest",
    land: "Asia",
    category: "thrill",
    description: "A high-speed coaster confronting the legendary Yeti.",
    x: 70,
    y: 38,
    baseWait: 35,
    trend: "down",
    lightningLane: true,
    height: '44" (112 cm) minimum',
  },
  {
    id: "ak-safari",
    parkId: "animal-kingdom",
    name: "Kilimanjaro Safaris",
    land: "Africa",
    category: "family",
    description:
      "A real safari across 110 acres of African savanna and live wildlife.",
    x: 50,
    y: 28,
    baseWait: 30,
    trend: "flat",
    lightningLane: true,
  },
  {
    id: "ak-dinosaur",
    parkId: "animal-kingdom",
    name: "DINOSAUR",
    land: "DinoLand U.S.A.",
    category: "thrill",
    description: "A turbulent time-travel mission to rescue an Iguanodon.",
    x: 78,
    y: 60,
    baseWait: 25,
    trend: "down",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
];

export function getPark(parkId: string): Park | undefined {
  return PARKS.find((p) => p.id === parkId);
}

export function getRidesForPark(parkId: ParkId): Ride[] {
  return RIDES.filter((r) => r.parkId === parkId);
}

export function getRide(rideId: string): Ride | undefined {
  return RIDES.find((r) => r.id === rideId);
}
