import type { Park, ParkId, Ride } from "./types";

export const PARKS: Park[] = [
  {
    id: "magic-kingdom",
    name: "Magic Kingdom",
    shortName: "MK",
    resort: "Walt Disney World",
    tagline: "The classic Disney experience",
    status: "Open",
    crowd: "High",
    hours: "9:00 AM — 11:00 PM",
    themeHex: "#6366f1",
    themeAccentHex: "#a5b4fc",
    lat: 28.4177,
    lng: -81.5812,
    zoom: 17,
  },
  {
    id: "epcot",
    name: "EPCOT",
    shortName: "EP",
    resort: "Walt Disney World",
    tagline: "Future tech meets world cultures",
    status: "Open",
    crowd: "Moderate",
    hours: "9:00 AM — 9:00 PM",
    themeHex: "#0ea5e9",
    themeAccentHex: "#7dd3fc",
    lat: 28.3747,
    lng: -81.5494,
    zoom: 17,
  },
  {
    id: "hollywood-studios",
    name: "Hollywood Studios",
    shortName: "HS",
    resort: "Walt Disney World",
    tagline: "Movies, magic, and Star Wars",
    status: "Open",
    crowd: "High",
    hours: "8:30 AM — 9:30 PM",
    themeHex: "#ef4444",
    themeAccentHex: "#fca5a5",
    lat: 28.3575,
    lng: -81.5582,
    zoom: 17,
  },
  {
    id: "animal-kingdom",
    name: "Animal Kingdom",
    shortName: "AK",
    resort: "Walt Disney World",
    tagline: "Wildlife, adventure, and Pandora",
    status: "Open",
    crowd: "Low",
    hours: "8:00 AM — 8:00 PM",
    themeHex: "#10b981",
    themeAccentHex: "#6ee7b7",
    lat: 28.3553,
    lng: -81.5901,
    zoom: 16,
  },
  {
    id: "disneyland",
    name: "Disneyland Park",
    shortName: "DL",
    resort: "Disneyland Resort",
    tagline: "The original — where it all began",
    status: "Open",
    crowd: "High",
    hours: "8:00 AM — 12:00 AM",
    themeHex: "#ec4899",
    themeAccentHex: "#f9a8d4",
    lat: 33.8121,
    lng: -117.919,
    zoom: 17,
  },
  {
    id: "california-adventure",
    name: "Disney California Adventure",
    shortName: "DCA",
    resort: "Disneyland Resort",
    tagline: "Pixar Pier, Cars Land, and beyond",
    status: "Open",
    crowd: "Moderate",
    hours: "9:00 AM — 10:00 PM",
    themeHex: "#f97316",
    themeAccentHex: "#fdba74",
    lat: 33.8067,
    lng: -117.9209,
    zoom: 17,
  },
];

export const RIDES: Ride[] = [
  // Magic Kingdom
  {
    id: "mk-space-mountain",
    parkId: "magic-kingdom",
    name: "Space Mountain",
    land: "Tomorrowland",
    category: "thrill",
    description:
      "Blast through the cosmos on a high-speed indoor coaster in near total darkness.",
    x: 72,
    y: 38,
    baseWait: 65,
    trend: "up",
    lightningLane: true,
    height: '44" (112 cm) minimum',
  },
  {
    id: "mk-seven-dwarfs",
    parkId: "magic-kingdom",
    name: "Seven Dwarfs Mine Train",
    land: "Fantasyland",
    category: "family",
    description:
      "A swaying mine-cart coaster through the diamond mines from Snow White.",
    x: 50,
    y: 30,
    baseWait: 80,
    trend: "up",
    lightningLane: true,
    height: '38" (97 cm) minimum',
  },
  {
    id: "mk-thunder-mountain",
    parkId: "magic-kingdom",
    name: "Big Thunder Mountain",
    land: "Frontierland",
    category: "thrill",
    description:
      "The wildest ride in the wilderness — a runaway mine train coaster.",
    x: 26,
    y: 40,
    baseWait: 45,
    trend: "flat",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "mk-pirates",
    parkId: "magic-kingdom",
    name: "Pirates of the Caribbean",
    land: "Adventureland",
    category: "family",
    description:
      "A scenic boat ride through swashbuckling pirate adventures.",
    x: 22,
    y: 58,
    baseWait: 25,
    trend: "down",
    lightningLane: false,
  },
  {
    id: "mk-haunted-mansion",
    parkId: "magic-kingdom",
    name: "Haunted Mansion",
    land: "Liberty Square",
    category: "family",
    description:
      "Doom buggies tour a manor with 999 happy haunts — and room for one more.",
    x: 38,
    y: 50,
    baseWait: 35,
    trend: "flat",
    lightningLane: true,
  },
  {
    id: "mk-jungle-cruise",
    parkId: "magic-kingdom",
    name: "Jungle Cruise",
    land: "Adventureland",
    category: "family",
    description:
      "A skipper-led river cruise through the rivers of the world. Puns included.",
    x: 30,
    y: 62,
    baseWait: 40,
    trend: "up",
    lightningLane: true,
  },
  {
    id: "mk-peter-pan",
    parkId: "magic-kingdom",
    name: "Peter Pan's Flight",
    land: "Fantasyland",
    category: "kids",
    description: "Soar over London and Neverland aboard a flying pirate ship.",
    x: 56,
    y: 36,
    baseWait: 70,
    trend: "up",
    lightningLane: true,
  },
  {
    id: "mk-tiana",
    parkId: "magic-kingdom",
    name: "Tiana's Bayou Adventure",
    land: "Frontierland",
    category: "family",
    description:
      "Plunge into the bayou for a musical journey with Princess Tiana and friends.",
    x: 18,
    y: 48,
    baseWait: 95,
    trend: "up",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },

  // EPCOT
  {
    id: "ep-guardians",
    parkId: "epcot",
    name: "Guardians of the Galaxy: Cosmic Rewind",
    land: "World Discovery",
    category: "thrill",
    description:
      "A reverse-launch coaster that rotates 360° to follow the action.",
    x: 64,
    y: 38,
    baseWait: 90,
    trend: "up",
    lightningLane: true,
    height: '42" (107 cm) minimum',
  },
  {
    id: "ep-test-track",
    parkId: "epcot",
    name: "Test Track",
    land: "World Discovery",
    category: "thrill",
    description:
      "Design your own concept car, then put it through its paces at 60+ mph.",
    x: 70,
    y: 56,
    baseWait: 60,
    trend: "flat",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "ep-soarin",
    parkId: "epcot",
    name: "Soarin' Around the World",
    land: "World Nature",
    category: "family",
    description:
      "Hang glide over the planet's most iconic landmarks in stunning IMAX scale.",
    x: 30,
    y: 46,
    baseWait: 45,
    trend: "down",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "ep-frozen",
    parkId: "epcot",
    name: "Frozen Ever After",
    land: "World Showcase — Norway",
    category: "family",
    description:
      "A musical boat ride through Arendelle with Anna, Elsa, and Olaf.",
    x: 24,
    y: 70,
    baseWait: 75,
    trend: "up",
    lightningLane: true,
  },
  {
    id: "ep-remy",
    parkId: "epcot",
    name: "Remy's Ratatouille Adventure",
    land: "World Showcase — France",
    category: "family",
    description: "Shrink to rat-size and scurry through Gusteau's restaurant.",
    x: 38,
    y: 78,
    baseWait: 55,
    trend: "flat",
    lightningLane: true,
  },
  {
    id: "ep-spaceship-earth",
    parkId: "epcot",
    name: "Spaceship Earth",
    land: "World Celebration",
    category: "family",
    description:
      "An iconic journey through the history of human communication.",
    x: 50,
    y: 28,
    baseWait: 20,
    trend: "down",
    lightningLane: false,
  },

  // Hollywood Studios
  {
    id: "hs-rise",
    parkId: "hollywood-studios",
    name: "Rise of the Resistance",
    land: "Galaxy's Edge",
    category: "thrill",
    description:
      "The most ambitious Disney ride ever — board a Star Destroyer and escape.",
    x: 22,
    y: 38,
    baseWait: 110,
    trend: "up",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "hs-millennium",
    parkId: "hollywood-studios",
    name: "Millennium Falcon: Smugglers Run",
    land: "Galaxy's Edge",
    category: "family",
    description: "Pilot the fastest hunk of junk in the galaxy on a smuggling job.",
    x: 28,
    y: 50,
    baseWait: 50,
    trend: "flat",
    lightningLane: true,
    height: '38" (97 cm) minimum',
  },
  {
    id: "hs-slinky",
    parkId: "hollywood-studios",
    name: "Slinky Dog Dash",
    land: "Toy Story Land",
    category: "family",
    description: "A backyard family coaster that twists, turns, and dashes.",
    x: 60,
    y: 64,
    baseWait: 70,
    trend: "up",
    lightningLane: true,
    height: '38" (97 cm) minimum',
  },
  {
    id: "hs-tower",
    parkId: "hollywood-studios",
    name: "Tower of Terror",
    land: "Sunset Boulevard",
    category: "thrill",
    description: "A haunted hotel free-fall drop through the Twilight Zone.",
    x: 78,
    y: 44,
    baseWait: 55,
    trend: "flat",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "hs-rocknroller",
    parkId: "hollywood-studios",
    name: "Rock 'n' Roller Coaster",
    land: "Sunset Boulevard",
    category: "thrill",
    description: "Launched coaster scored to Aerosmith. 0–60 in 2.8 seconds.",
    x: 82,
    y: 52,
    baseWait: 65,
    trend: "up",
    lightningLane: true,
    height: '48" (122 cm) minimum',
  },
  {
    id: "hs-runaway-railway",
    parkId: "hollywood-studios",
    name: "Mickey & Minnie's Runaway Railway",
    land: "Hollywood Boulevard",
    category: "family",
    description:
      "Step into a Mickey Mouse cartoon for a wonderfully unpredictable ride.",
    x: 50,
    y: 30,
    baseWait: 40,
    trend: "down",
    lightningLane: true,
  },

  // Animal Kingdom
  {
    id: "ak-flight-of-passage",
    parkId: "animal-kingdom",
    name: "Avatar Flight of Passage",
    land: "Pandora",
    category: "thrill",
    description:
      "Bond with a banshee and soar across the moon of Pandora in 3D.",
    x: 26,
    y: 50,
    baseWait: 105,
    trend: "up",
    lightningLane: true,
    height: '44" (112 cm) minimum',
  },
  {
    id: "ak-navi",
    parkId: "animal-kingdom",
    name: "Na'vi River Journey",
    land: "Pandora",
    category: "family",
    description: "A serene boat ride through the bioluminescent rainforest.",
    x: 32,
    y: 60,
    baseWait: 60,
    trend: "flat",
    lightningLane: true,
  },
  {
    id: "ak-everest",
    parkId: "animal-kingdom",
    name: "Expedition Everest",
    land: "Asia",
    category: "thrill",
    description: "A high-speed coaster confronting the legendary Yeti.",
    x: 70,
    y: 38,
    baseWait: 35,
    trend: "down",
    lightningLane: true,
    height: '44" (112 cm) minimum',
  },
  {
    id: "ak-safari",
    parkId: "animal-kingdom",
    name: "Kilimanjaro Safaris",
    land: "Africa",
    category: "family",
    description:
      "A real safari across 110 acres of African savanna and live wildlife.",
    x: 50,
    y: 28,
    baseWait: 30,
    trend: "flat",
    lightningLane: true,
  },
  {
    id: "ak-dinosaur",
    parkId: "animal-kingdom",
    name: "DINOSAUR",
    land: "DinoLand U.S.A.",
    category: "thrill",
    description: "A turbulent time-travel mission to rescue an Iguanodon.",
    x: 78,
    y: 60,
    baseWait: 25,
    trend: "down",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },

  // Disneyland Park
  {
    id: "dl-rise",
    parkId: "disneyland",
    name: "Star Wars: Rise of the Resistance",
    land: "Galaxy's Edge",
    category: "thrill",
    description:
      "Disney's most ambitious ride — board a Star Destroyer and escape the First Order.",
    x: 22,
    y: 22,
    baseWait: 105,
    trend: "up",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "dl-millennium-falcon",
    parkId: "disneyland",
    name: "Millennium Falcon: Smugglers Run",
    land: "Galaxy's Edge",
    category: "family",
    description:
      "Pilot the fastest hunk of junk in the galaxy on a smuggling job.",
    x: 30,
    y: 30,
    baseWait: 45,
    trend: "flat",
    lightningLane: true,
    height: '38" (97 cm) minimum',
  },
  {
    id: "dl-space-mountain",
    parkId: "disneyland",
    name: "Space Mountain",
    land: "Tomorrowland",
    category: "thrill",
    description:
      "Disneyland's iconic high-speed indoor coaster through the cosmos.",
    x: 72,
    y: 38,
    baseWait: 60,
    trend: "up",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "dl-matterhorn",
    parkId: "disneyland",
    name: "Matterhorn Bobsleds",
    land: "Fantasyland",
    category: "thrill",
    description:
      "A bobsled race down the Matterhorn — and a run-in with the Abominable Snowman.",
    x: 50,
    y: 26,
    baseWait: 35,
    trend: "flat",
    lightningLane: false,
    height: '42" (107 cm) minimum',
  },
  {
    id: "dl-indy",
    parkId: "disneyland",
    name: "Indiana Jones Adventure",
    land: "Adventureland",
    category: "thrill",
    description:
      "An off-road jeep ride into the Temple of the Forbidden Eye.",
    x: 22,
    y: 60,
    baseWait: 70,
    trend: "up",
    lightningLane: true,
    height: '46" (117 cm) minimum',
  },
  {
    id: "dl-pirates",
    parkId: "disneyland",
    name: "Pirates of the Caribbean",
    land: "New Orleans Square",
    category: "family",
    description:
      "The original boat ride through swashbuckling pirate adventures.",
    x: 28,
    y: 70,
    baseWait: 25,
    trend: "down",
    lightningLane: false,
  },
  {
    id: "dl-haunted-mansion",
    parkId: "disneyland",
    name: "Haunted Mansion",
    land: "New Orleans Square",
    category: "family",
    description:
      "Doom buggies tour a manor with 999 happy haunts — and room for one more.",
    x: 36,
    y: 65,
    baseWait: 40,
    trend: "flat",
    lightningLane: true,
  },
  {
    id: "dl-thunder-mountain",
    parkId: "disneyland",
    name: "Big Thunder Mountain Railroad",
    land: "Frontierland",
    category: "thrill",
    description:
      "The wildest ride in the wilderness — a runaway mine train coaster.",
    x: 30,
    y: 50,
    baseWait: 40,
    trend: "flat",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "dl-tiana",
    parkId: "disneyland",
    name: "Tiana's Bayou Adventure",
    land: "Critter Country",
    category: "family",
    description:
      "A musical journey into the bayou with Princess Tiana and friends.",
    x: 18,
    y: 76,
    baseWait: 65,
    trend: "up",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },

  // Disney California Adventure
  {
    id: "dca-radiator-springs",
    parkId: "california-adventure",
    name: "Radiator Springs Racers",
    land: "Cars Land",
    category: "thrill",
    description:
      "Race through Ornament Valley in a real-life recreation of Cars' Radiator Springs.",
    x: 70,
    y: 28,
    baseWait: 90,
    trend: "up",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "dca-incredicoaster",
    parkId: "california-adventure",
    name: "Incredicoaster",
    land: "Pixar Pier",
    category: "thrill",
    description:
      "A launched, looping coaster scored to The Incredibles soundtrack.",
    x: 78,
    y: 60,
    baseWait: 55,
    trend: "flat",
    lightningLane: true,
    height: '48" (122 cm) minimum',
  },
  {
    id: "dca-guardians",
    parkId: "california-adventure",
    name: "Guardians of the Galaxy: Mission BREAKOUT!",
    land: "Avengers Campus",
    category: "thrill",
    description:
      "A free-fall drop ride through the Collector's fortress, scored to a Guardians playlist.",
    x: 30,
    y: 25,
    baseWait: 60,
    trend: "up",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "dca-webslingers",
    parkId: "california-adventure",
    name: "WEB SLINGERS: A Spider-Man Adventure",
    land: "Avengers Campus",
    category: "family",
    description:
      "Sling webs alongside Spider-Man to wrangle runaway Spider-Bots.",
    x: 26,
    y: 32,
    baseWait: 50,
    trend: "flat",
    lightningLane: true,
  },
  {
    id: "dca-soarin",
    parkId: "california-adventure",
    name: "Soarin' Around the World",
    land: "Grizzly Peak",
    category: "family",
    description:
      "Hang glide over the planet's most iconic landmarks in stunning IMAX scale.",
    x: 22,
    y: 50,
    baseWait: 40,
    trend: "down",
    lightningLane: true,
    height: '40" (102 cm) minimum',
  },
  {
    id: "dca-grizzly-river",
    parkId: "california-adventure",
    name: "Grizzly River Run",
    land: "Grizzly Peak",
    category: "family",
    description:
      "A whitewater raft adventure down the slopes of Grizzly Peak. Expect to get soaked.",
    x: 28,
    y: 58,
    baseWait: 30,
    trend: "flat",
    lightningLane: true,
    height: '42" (107 cm) minimum',
  },
  {
    id: "dca-toy-story",
    parkId: "california-adventure",
    name: "Toy Story Midway Mania!",
    land: "Pixar Pier",
    category: "family",
    description:
      "A 4D shooting gallery hosted by Woody, Buzz, and the Toy Story crew.",
    x: 72,
    y: 65,
    baseWait: 35,
    trend: "flat",
    lightningLane: true,
  },
  {
    id: "dca-pixar-pal",
    parkId: "california-adventure",
    name: "Pixar Pal-A-Round",
    land: "Pixar Pier",
    category: "family",
    description:
      "A 150-foot Ferris wheel with a Pixar twist — pick a swinging or non-swinging gondola.",
    x: 80,
    y: 70,
    baseWait: 25,
    trend: "down",
    lightningLane: false,
  },
];

export function getPark(parkId: string): Park | undefined {
  return PARKS.find((p) => p.id === parkId);
}

export function getRidesForPark(parkId: ParkId): Ride[] {
  return RIDES.filter((r) => r.parkId === parkId);
}

export function getRide(rideId: string): Ride | undefined {
  return RIDES.find((r) => r.id === rideId);
}
