/**
 * Parkio Daily — daily theme-park briefing content store.
 *
 * Posts live as JSON files in `content/guide/daily/{slug}.json`.
 * One file per day, generated by an automation (see docs/AUTOMATION.md)
 * and committed to git. Cloudflare Pages auto-rebuilds on push, which
 * publishes the post.
 *
 * The JSON schema below is the contract the automation MUST produce.
 * Type-checked at build time when Next.js statically renders pages.
 */

import fs from "node:fs";
import path from "node:path";
import type { ParkId } from "./types";

/* ──────────────────────── Types ──────────────────────── */

export type DailySectionKind =
  | "breaking-news"
  | "big-news"
  | "top-stories"
  | "icymi"
  | "spotlight"
  | "videos";

/** Source attribution shown next to a news item. Optional. */
export interface DailySource {
  label: string;
  url: string;
}

/**
 * One news bullet inside Breaking / Big / Top / ICYMI sections.
 * `body` is plain text (no markdown) — line breaks are preserved as
 * paragraph breaks at render time.
 */
export interface DailyNewsItem {
  title: string;
  body: string;
  source?: DailySource;
  /**
   * Optional deep-link into Parkio's live park page. When set, the
   * news item renders a "Check live data →" inline link.
   */
  parkSlug?: ParkId;
}

/**
 * Spotlight items are the long-form moment of the day — a featured
 * park, a feature explainer, a deep dive. Drives heavily into the
 * live product via the optional CTA.
 */
export interface DailySpotlightItem {
  title: string;
  body: string;
  ctaParkSlug?: ParkId;
  ctaLabel?: string;
}

/**
 * "Most Watched Disney Videos" rail. Thumbnails + click-through to
 * the source (YouTube, TikTok, etc.). Parkio doesn't host or embed
 * videos — just curates and links out.
 */
export interface DailyVideoItem {
  title: string;
  channel: string;
  url: string;
  thumbnailUrl?: string;
}

export type DailySection =
  | { kind: "breaking-news"; items: DailyNewsItem[] }
  | { kind: "big-news"; items: DailyNewsItem[] }
  | { kind: "top-stories"; items: DailyNewsItem[] }
  | { kind: "icymi"; items: DailyNewsItem[] }
  | { kind: "spotlight"; items: DailySpotlightItem[] }
  | { kind: "videos"; items: DailyVideoItem[] };

export interface DailyPost {
  /** URL slug. Convention: `disney-park-news-YYYY-MM-DD`. */
  slug: string;
  /** Discriminator for the unified post-type union (vs. evergreen guides). */
  type: "daily-briefing";
  title: string;
  /**
   * ISO date "YYYY-MM-DD" — the day the briefing covers. Used for
   * sort order on the index, and for the human-readable date in
   * the article header.
   */
  publishedAt: string;
  /**
   * Optional ISO timestamp with offset — when the file was last
   * regenerated. Used for sitemap lastModified and for the "Updated
   * X ago" hint on the detail page.
   */
  updatedAt?: string;
  /**
   * 1–2 sentences. Becomes the SEO meta description AND the card
   * preview on the index AND the social/newsletter teaser. Keep
   * under ~160 chars.
   */
  summary: string;
  sections: DailySection[];
}

/* ──────────────────────── Loader ──────────────────────── */

const DAILY_DIR = path.join(process.cwd(), "content", "guide", "daily");

function dirExists(p: string): boolean {
  try {
    return fs.statSync(p).isDirectory();
  } catch {
    return false;
  }
}

/** All daily-briefing slugs present on disk. Used by generateStaticParams. */
export function listDailySlugs(): string[] {
  if (!dirExists(DAILY_DIR)) return [];
  return fs
    .readdirSync(DAILY_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""));
}

/** Read + parse a single daily-briefing file. Returns null on any error. */
export function getDailyPost(slug: string): DailyPost | null {
  if (!dirExists(DAILY_DIR)) return null;
  const file = path.join(DAILY_DIR, `${slug}.json`);
  if (!fs.existsSync(file)) return null;
  try {
    const raw = JSON.parse(fs.readFileSync(file, "utf8")) as DailyPost;
    // Defensive: ensure type discriminator is set even if the source
    // file omitted it. Lets older posts work after the schema added it.
    if (raw.type !== "daily-briefing") {
      return { ...raw, type: "daily-briefing" };
    }
    return raw;
  } catch {
    return null;
  }
}

/** All daily briefings, sorted newest-first. */
export function listDailyPosts(): DailyPost[] {
  return listDailySlugs()
    .map((slug) => getDailyPost(slug))
    .filter((p): p is DailyPost => p !== null)
    .sort((a, b) => (a.publishedAt < b.publishedAt ? 1 : -1));
}

/* ──────────────────────── Display helpers ──────────────────────── */

const SECTION_TITLES: Record<DailySectionKind, string> = {
  "breaking-news": "Breaking news",
  "big-news": "Big news",
  "top-stories": "Top stories",
  icymi: "ICYMI",
  spotlight: "Spotlight",
  videos: "Most watched Disney videos",
};

export function sectionTitle(kind: DailySectionKind): string {
  return SECTION_TITLES[kind];
}

export function sectionEyebrow(kind: DailySectionKind): string {
  // Used as the small uppercase label above the section heading.
  switch (kind) {
    case "breaking-news":
      return "01 · Breaking";
    case "big-news":
      return "02 · Big news";
    case "top-stories":
      return "03 · Top stories";
    case "icymi":
      return "04 · ICYMI";
    case "spotlight":
      return "05 · Spotlight";
    case "videos":
      return "06 · Most watched";
  }
}

/** Long-form ISO → "April 26, 2026" using en-US for stable output. */
export function formatBriefingDate(isoDate: string): string {
  const ts = Date.parse(isoDate);
  if (Number.isNaN(ts)) return isoDate;
  return new Date(ts).toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC", // we get YYYY-MM-DD so UTC formatting is stable
  });
}
