/**
 * Parkio Daily — daily theme-park briefing content store.
 *
 * Posts live as JSON files at `content/guide/daily/{slug}.json`.
 * One file per day, generated by an automation (see docs/AUTOMATION.md)
 * and committed to git. Cloudflare Pages auto-rebuilds on push.
 *
 * The JSON schema is deliberately flat and human-readable so an n8n
 * workflow can produce it without contortions:
 *
 *   {
 *     "title":   "Disney Park News — April 26, 2026",
 *     "slug":    "disney-park-news-2026-04-26",
 *     "date":    "2026-04-26",
 *     "teaser":  "1–2 sentence hook used for SEO + email teaser.",
 *     "rightNow": {
 *       "headline": "Best rides right now",
 *       "rides": [
 *         { "name": "TRON", "parkSlug": "magic-kingdom", "note": "..." }
 *       ]
 *     },
 *     "sections": {
 *       "breaking":   [ { "title", "body", "parkSlug?", "source?": {...} } ],
 *       "bignews":    [ ... ],
 *       "topstories": [ ... ],
 *       "icymi":      [ ... ],
 *       "spotlight":  [ { "title", "body", "parkSlug?", "ctaLabel?" } ]
 *     },
 *     "videos": [ { "title", "channel", "url", "thumbnailUrl?" } ]
 *   }
 *
 * Section ORDER is fixed by the renderer (breaking → bignews → top
 * stories → icymi → spotlight → videos). n8n omits any section that
 * has nothing to say.
 */

import fs from "node:fs";
import path from "node:path";
import type { ParkId } from "./types";

/* ──────────────────────── Item types ──────────────────────── */

export interface DailyNewsItem {
  title: string;
  body: string;
  /** Deep-link to a park page when the story is park-specific. */
  parkSlug?: ParkId;
  source?: { label: string; url: string };
}

export interface DailySpotlightItem {
  title: string;
  body: string;
  parkSlug?: ParkId;
  /** Optional CTA button label override. Defaults to "Open {park} on Parkio". */
  ctaLabel?: string;
}

export interface DailyVideoItem {
  title: string;
  channel: string;
  url: string;
  thumbnailUrl?: string;
}

export interface DailyRightNowRide {
  name: string;
  parkSlug?: ParkId;
  /** Short editorial note, e.g. "Walk-on at opening". */
  note?: string;
}

export interface DailyRightNow {
  /** Section headline. Defaults to "Best rides right now". */
  headline?: string;
  rides: DailyRightNowRide[];
}

/* ──────────────────────── Section keys ──────────────────────── */

export type DailySectionKey =
  | "breaking"
  | "bignews"
  | "topstories"
  | "icymi"
  | "spotlight";

/** Renderer iterates this order; n8n doesn't have to. */
export const SECTION_ORDER: DailySectionKey[] = [
  "breaking",
  "bignews",
  "topstories",
  "icymi",
  "spotlight",
];

const SECTION_TITLES: Record<DailySectionKey, string> = {
  breaking: "Breaking news",
  bignews: "Big news",
  topstories: "Top stories",
  icymi: "ICYMI",
  spotlight: "Spotlight",
};

const SECTION_EYEBROWS: Record<DailySectionKey, string> = {
  breaking: "01 · Breaking",
  bignews: "02 · Big news",
  topstories: "03 · Top stories",
  icymi: "04 · ICYMI",
  spotlight: "05 · Spotlight",
};

export function sectionTitle(key: DailySectionKey): string {
  return SECTION_TITLES[key];
}

export function sectionEyebrow(key: DailySectionKey): string {
  return SECTION_EYEBROWS[key];
}

/* ──────────────────────── Post shape ──────────────────────── */

export interface DailyPost {
  slug: string;
  title: string;
  /** ISO date "YYYY-MM-DD" — the day the briefing covers. */
  date: string;
  /** 1–2 sentences. SEO description + email teaser + card preview. ~160 chars. */
  teaser: string;
  /** Above-the-fold "Right now" picks. 2–3 rides recommended. Optional. */
  rightNow?: DailyRightNow;
  /** Body sections — any subset present. Renderer fixes the order. */
  sections?: Partial<Record<DailySectionKey, DailyNewsItem[] | DailySpotlightItem[]>>;
  /** "Most watched Disney videos" rail. Top-level for n8n simplicity. */
  videos?: DailyVideoItem[];
  /** Optional ISO timestamp — when the file was last regenerated. */
  updatedAt?: string;
  /** Discriminator for the unified post-type union (vs. evergreen guides). */
  type?: "daily-briefing";
}

/* ──────────────────────── Loader ──────────────────────── */

const DAILY_DIR = path.join(process.cwd(), "content", "guide", "daily");

function dirExists(p: string): boolean {
  try {
    return fs.statSync(p).isDirectory();
  } catch {
    return false;
  }
}

/** All daily-briefing slugs present on disk. Used by generateStaticParams. */
export function listDailySlugs(): string[] {
  if (!dirExists(DAILY_DIR)) return [];
  return fs
    .readdirSync(DAILY_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""));
}

/** Read + parse a single daily-briefing file. Returns null on any error. */
export function getDailyPost(slug: string): DailyPost | null {
  if (!dirExists(DAILY_DIR)) return null;
  const file = path.join(DAILY_DIR, `${slug}.json`);
  if (!fs.existsSync(file)) return null;
  try {
    const raw = JSON.parse(fs.readFileSync(file, "utf8")) as DailyPost;
    // Ensure a stable shape even if the source omitted optional fields.
    return {
      ...raw,
      type: "daily-briefing",
      sections: raw.sections ?? {},
      videos: raw.videos ?? [],
    };
  } catch {
    return null;
  }
}

/** All daily briefings, sorted newest-first. */
export function listDailyPosts(): DailyPost[] {
  return listDailySlugs()
    .map((slug) => getDailyPost(slug))
    .filter((p): p is DailyPost => p !== null)
    .sort((a, b) => (a.date < b.date ? 1 : -1));
}

/* ──────────────────────── Display helpers ──────────────────────── */

/** ISO "YYYY-MM-DD" → "Sunday, April 26, 2026". Stable across viewer timezones. */
export function formatBriefingDate(isoDate: string): string {
  const ts = Date.parse(isoDate);
  if (Number.isNaN(ts)) return isoDate;
  return new Date(ts).toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });
}

/** Test whether a section has any items to render. Used by the iterator. */
export function hasItems<T>(
  items: T[] | undefined,
): items is T[] {
  return Array.isArray(items) && items.length > 0;
}
