/**
 * URL guards for content that Parkio did not author.
 *
 * Daily briefings are generated by an LLM from third-party RSS feeds and
 * YouTube metadata, so every URL inside `content/guide/daily/*.json` is
 * effectively untrusted input: a `javascript:` or `data:` href would run
 * on click, and an unescaped value interpolated into a CSS `url()` can
 * break out and inject arbitrary declarations.
 */

/** Absolute http(s) URL, or null when the value is anything else. */
export function safeExternalUrl(url: string | undefined | null): string | null {
  if (!url) return null;
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return null;
  }
  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") return null;
  return parsed.toString();
}

/** Same-origin path (`/foo`), or null. Protocol-relative `//host` is rejected. */
export function safeInternalHref(
  href: string | undefined | null,
): string | null {
  if (!href) return null;
  if (!href.startsWith("/") || href.startsWith("//")) return null;
  return href;
}

/** Value safe to interpolate into `url(...)` in a CSS declaration. */
export function safeCssUrl(url: string | undefined | null): string | null {
  const safe = safeExternalUrl(url);
  if (!safe) return null;
  if (/["'()\\\s]/.test(safe)) return null;
  return safe;
}
